export const OBJECT_KEYS = {checkpoint:'flowCheckpoint',prepare:'flowPrepare',weights:'flowWeights',input:'flowInput',activation:'flowActivation',linear:'flowLinear',cache:'flowCache',attention:'flowAttention'};
export const objectKey = (m,name) => name==='activation'&&!m.low?'flowDirect':OBJECT_KEYS[name];

export const flowI18n = {
  zh: {
    flowDirect:'不转换激活', flowEachFP8:'每次前向 · FP8', flowCastWrite:'K/V → FP8 写入',
    flowGemmInfo:'低精度激活与常驻权重在这里相乘，两侧 scale 一起参与计算，输出回到 BF16。下一轮继续用同一份权重，只换新的激活。',
    flowDynamicInfo:'根据当前每行输入计算 scale，再把该行转成 FP8。Prefill 有 4 行，Decode 只有 1 行；输入变化时，scale 也可能变化。',
    flowStaticInfo:'scale 提前保存在 checkpoint 中，每轮沿用；但新的激活仍然每次都要转换。放大的输入可能超出固定范围，造成裁剪。',
    flowPrefillInfo:'没有历史前缀时，直接用刚算出的 Q/K/V 做 Attention，然后把 K/V 存入缓存，留给后续 Decode。',
    flowDecodeInfo:'先写入本轮新 K/V，再用本轮 Q 读取历史和新 KV。蓝色读框覆盖整个有效前缀，旧数据不用重新计算。',
    flowTitle:'同一层里的数据流', flowHint:'点选对象看数值；箭头表示当前操作的数据依赖。',
    flowCheckpoint:'Checkpoint', flowPrepare:'加载时准备', flowWeights:'GPU 常驻权重',
    flowInput:'本轮激活', flowActivation:'激活转换', flowLinear:'Linear · QKV 投影', flowAttention:'Attention', flowCache:'KV Cache',
    flowOffline:'离线产物', flowOnce:'只做一次', flowEach:'每次前向', flowKeep:'跨轮留存',
    flowWeightCast:'量化 + 布局整理', flowWeightSaved:'读取 scale · 整理布局', flowWeightBase:'保持 BF16',
    flowWaiting:'等待输入', flowAvailable:'数值就绪', flowUnloaded:'尚未加载', flowFuture:'待执行', flowActive:'下一步', flowPassed:'已完成',
    flowReused:'复用 · 不重新量化', flowRows:'输入行', flowBypass:'直接使用 BF16',
    flowDynamic:'每行现算 scale', flowStatic:'复用 checkpoint scale', flowKVFixed:'复用层 scale',
    flowPayload:'数据', flowMetadata:'scale', flowPayloadHint:'条长只比较数据字节；scale 开销另计，张量形状不变。',
    flowWeightCount:'权重量化', flowActivationCount:'激活量化', flowCalls:'次',
    flowNew:'新增', flowOld:'保留', flowRead:'读', flowWrite:'写', flowFull:'容量', flowHeld:'预留',
    flowFresh:'新 K/V', flowQuery:'Q', flowReadLabel:'读历史 + 新 KV', flowWriteLabel:'K/V → 存储',
    flowPhaseHint:'本例 Prefill 直接用新 K/V 做 Attention；Decode 先写新 KV，再读整个前缀。',
    flowSelection:'对象检查', flowFollow:'跟随当前步骤', flowRow:'检查输入行', flowValues:'完整矩阵与数值',
    flowOriginal:'原值', flowEncoded:'编码', flowRestored:'重建', flowExample:'第 1 个通道', flowScale:'使用的 scale',
    flowCheckpointInfo:'文件可能是原始 BF16，也可能已经保存 FP8 权重与 scale。文件格式决定加载阶段是否还要量化。',
    flowWeightsInfo:'准备完成后留在 GPU。Prefill 和每次 Decode 都读取这同一份权重；数值和 scale 不随输入更新。',
    flowInputInfo:'这是当前层的输入，不是整个模型的原始 Token。Prefill 一次处理 4 行；后续每轮 Decode 只增加 1 行。',
    flowCacheInfo:'缓存池先创建。为新位置分配地址后才写入；旧槽位保留，Decode 读取整个已写前缀。点击槽位可检查 K/V。',
    flowBaselineInfo:'该部署路径不转换激活，BF16 输入直接进入线性算子。KV 存储格式仍独立选择。',
    flowLayerScope:'局部层示意 · 省略 RoPE、输出投影与 MLP；不是完整模型前向',
    flowEvidence:'实现依据、配置与边界', flowEvidenceHint:'以固定 SGLang / FlashInfer 分支校验本例；不代表所有引擎的统一顺序。',
    flowWritePort:'写入', flowReadPort:'读取',
    flowSmallBoundary:'以 SGLang v0.4.6.post5 / FlashInfer 为例；非真实模型运行，压缩比不等于实测加速比。',
    flowCapacity:'已写 / 总槽位', flowReserve:'已分配', flowNoSlot:'选择已写入槽位查看数值。', flowSlotValues:'该槽重建 K / V',
    flowReadNow:'当前读取', flowTarget:'本轮写入地址', flowScaleLater:'转换完成后显示',
  },
  en: {
    flowDirect:'No activation cast', flowEachFP8:'Each pass · FP8', flowCastWrite:'K/V → FP8 write',
    flowGemmInfo:'Low-precision activations and resident weights meet here. Both scales enter the calculation; output returns to BF16. The next pass reuses the same weights with fresh activations.',
    flowDynamicInfo:'Compute a scale from each current input row, then cast that row to FP8. Prefill has four rows; Decode has one. New inputs can produce new scales.',
    flowStaticInfo:'Reuse the scale saved in the checkpoint, but still cast fresh activations on every pass. Amplified inputs can exceed the fixed range and be clipped.',
    flowPrefillInfo:'With no historical prefix, attend directly to fresh Q/K/V. Then store K/V for subsequent Decode passes.',
    flowDecodeInfo:'Write the new K/V first, then use current Q to read old and new KV. Blue read outlines cover the valid prefix; historical K/V need not be recomputed.',
    flowTitle:'Data flow inside one layer', flowHint:'Select an object to inspect it. Arrows show the current operation’s dependencies.',
    flowCheckpoint:'Checkpoint', flowPrepare:'Load-time preparation', flowWeights:'GPU-resident weights',
    flowInput:'Current activations', flowActivation:'Activation cast', flowLinear:'Linear · QKV projection', flowAttention:'Attention', flowCache:'KV Cache',
    flowOffline:'Offline artifact', flowOnce:'Once at startup', flowEach:'Every forward pass', flowKeep:'Retained across passes',
    flowWeightCast:'Quantize + arrange layout', flowWeightSaved:'Read scales · arrange layout', flowWeightBase:'Keep BF16',
    flowWaiting:'Awaiting input', flowAvailable:'Values ready', flowUnloaded:'Not loaded', flowFuture:'Pending', flowActive:'Next step', flowPassed:'Completed',
    flowReused:'Reuse · no recast', flowRows:'Input rows', flowBypass:'Use BF16 directly',
    flowDynamic:'Per-row scale', flowStatic:'Checkpoint scale', flowKVFixed:'Reuse layer scale',
    flowPayload:'Payload', flowMetadata:'Scales', flowPayloadHint:'Bar length compares payload bytes only; scales are counted separately. Tensor shape is unchanged.',
    flowWeightCount:'Weight conversions', flowActivationCount:'Activation conversions', flowCalls:'calls',
    flowNew:'New', flowOld:'Kept', flowRead:'Read', flowWrite:'Write', flowFull:'Capacity', flowHeld:'Held',
    flowFresh:'New K/V', flowQuery:'Q', flowReadLabel:'Read old + new KV', flowWriteLabel:'K/V → storage',
    flowPhaseHint:'This Prefill uses fresh K/V directly. Decode writes new KV, then reads the whole prefix.',
    flowSelection:'Object inspector', flowFollow:'Follow current step', flowRow:'Inspect input row', flowValues:'Full matrices & values',
    flowOriginal:'Original', flowEncoded:'Encoded', flowRestored:'Restored', flowExample:'First channel', flowScale:'Scale used',
    flowCheckpointInfo:'The file may contain original BF16 or already-quantized FP8 weights and scales. Its format determines whether loading needs a weight conversion.',
    flowWeightsInfo:'Once prepared, these weights stay on the GPU. Prefill and every Decode pass reuse the same values and scales, independent of changing inputs.',
    flowInputInfo:'These are inputs to the current layer, not raw model tokens. Prefill processes four rows together; each subsequent Decode pass adds one row.',
    flowCacheInfo:'Create the pool, reserve addresses, then write new positions. Old slots persist; Decode reads the written prefix. Select a slot to inspect K/V.',
    flowBaselineInfo:'This path does not quantize activations: BF16 inputs go directly to the linear kernel. KV storage precision is still independent.',
    flowLayerScope:'Local layer view · RoPE, output projection and MLP omitted; not a full forward pass',
    flowEvidence:'Implementation, configuration & boundaries', flowEvidenceHint:'Validated against a pinned SGLang / FlashInfer branch, not a universal engine execution order.',
    flowWritePort:'Write', flowReadPort:'Read',
    flowSmallBoundary:'SGLang v0.4.6.post5 / FlashInfer example, not real model execution. Compression is not a measured speedup.',
    flowCapacity:'Written / total slots', flowReserve:'Reserved addresses', flowNoSlot:'Select a written slot to inspect its values.', flowSlotValues:'Restored K / V in this slot',
    flowReadNow:'Reading now', flowTarget:'Write addresses this pass', flowScaleLater:'Shown after conversion',
  },
};
