import { FORMULAS } from './model.js';

export const getInitialLang = () => (typeof navigator !== 'undefined' && navigator.language?.toLowerCase().startsWith('zh') ? 'zh' : 'en');

export const i18n = {
  zh: {
    softmax: 'Softmax', architectureShortTitle: '历史怎样保存？', stageProgress: '整块算子阶段',
    title: 'Linear Attention 交互实验室',
    subtitle: '从历史表示、显存增长、计算复杂度与信息损失理解 Linear Attention 的设计取舍',
    exact: '精确 Softmax', linear: '朴素 Linear', gla: 'GLA', softmaxVs: 'Softmax 对照',
    reset: '重置', play: '播放', pause: '暂停', next: '下一步', zh: '中文', en: 'EN',
    experiment: '规模与维度', sequenceLength: '序列长度 N', contextLength: '上下文长度 N', keyDim: '键维度 dₖ', valueDim: '值维度 dᵥ', comparisonTarget: '对照目标',
    designLevel: '设计层', architectureTitle: '历史表示：逐 token KV Cache vs 固定压缩状态', architectureLead: 'Softmax 保存可独立寻址的历史槽位；Linear/GLA 把全部历史合并进固定大小状态。先看这种表示差异，再进入单个 token 的实现流水线。',
    executionContext: '执行上下文', decode: 'Decode', prefill: 'Prefill / 训练', growingKvCache: '随 N 增长的 KV Cache', pairwiseAttentionSurface: '全序列两两比较面', addressable: '可独立寻址', fixedRecurrentState: '固定递归状态', gatedFixedState: '带选择性遗忘的固定状态', compressed: '压缩摘要',
    softmaxDecodeVisual: '当前 query 连接不断增长的 KV Cache', softmaxPrefillVisual: '因果 Softmax 的 N 乘 N 两两比较面', softmaxDecodeLead: '每个历史 token 保留自己的 key 与 value；当前 query 可以分别匹配它们，但 KV Cache 与单步读取成本都会随上下文增长。', softmaxPrefillLead: '整段序列可并行计算，但逻辑上仍存在 N×N 的因果比较面，序列翻倍会让两两关系变为四倍。',
    logicalCells: '逻辑分数单元', moreSlots: '个额外 KV 槽位', chunksEnter: '并行 chunk 汇入', tokensEnter: '历史 token 汇入', fixedShape: '尺寸固定', linearCompressedLead: '历史不再保留独立槽位，而是通过外积累加进同一个 S 与 z；状态大小不随 N 增长。', glaCompressedLead: 'GLA 保留同样的固定状态结构，但会先衰减旧状态再写入当前 token，以管理有限容量。',
    persistentMemory: '持久历史存储', singleTokenWork: '单 token 读取', historyAccess: '历史访问方式', addressableHistory: '每个 KV 槽位可单独匹配', compressedHistory: '只能读取合并后的状态摘要', growthWithN: '随 N 增长', linearGrowth: '存储与单步计算线性增长', fixedGrowth: '状态尺寸与单步计算基本固定',
    logicalIntermediate: '逻辑中间结构', sequenceWork: '整段序列计算', parallelForm: '并行形式', matrixParallel: '矩阵并行', chunkwiseGla: '硬件友好的分块并行', prefixOrChunk: '前缀扫描或分块并行', informationForm: '信息组织', pairwiseSurface: '保留两两关系面', compressedSummary: '合并为有限状态摘要', comparisonAxis: '比较维度', elements: '元素',
    currentMemoryRatio: '按当前 N 估算，Softmax Decode 的 KV 元素约为固定状态的', breakEvenAt: '理论交叉点约在', notYetSaving: '当前短上下文下固定状态尚未体现显存优势', prefillFlashNote: '这里比较的是逻辑计算面；FlashAttention 可避免完整物化 N² 分数矩阵，但不会消除精确注意力的两两计算。',
    compressionCostTitle: '压缩不是免费午餐：可寻址历史变成有限状态', compressionCostLead: '相似 key 对应不同 value 时，Softmax 仍能分别选择；Linear 把它们合并进同一状态，可能出现碰撞、混合与细节丢失。', separateSlots: 'Softmax：槽位保持分离', querySelectsB: 'query 精确选择 B', softmaxRecallResult: '结果：B 仍可被直接定位，其他历史不会被永久混入它的槽位。', mergedState: '固定状态：A/B/C 合并', noTokenAddress: '没有 token 地址', linearCollisionResult: '结果：只能从混合状态读取，有限维度中可能出现状态碰撞。', glaCollisionResult: '结果：门控可压低旧碰撞，但也可能把仍有用的历史一起遗忘。',
    prefillFlowTitle: 'Prefill 一次性算子流：阶段处理整块矩阵或 chunk，不逐 token 扫描', prefillSoftmax0: '并行生成 Q/K/V', prefillSoftmax1: '构造因果分数面', prefillSoftmax2: '遮罩与 Softmax', prefillSoftmax3: '矩阵聚合 V', prefillLinear0: '并行特征映射', prefillLinear1: '生成 chunk 摘要', prefillLinear2: '前缀/分块扫描', prefillLinear3: '并行读取输出', prefillGla0: '映射并生成门控', prefillGla1: 'chunk 内并行', prefillGla2: '门控状态跨 chunk', prefillGla3: '并行读取输出',
    implementationDetailTitle: '第二层：展开单个 token 的真实 Decode 路径', implementationDetailLead: '宏观对比回答“为什么要压缩”；下面的流水线只负责回答“当前 token 如何写入、读取或匹配历史”。', detailAlgorithm: '实现细节算法', demoSequence: '8-token 缩略演示', prefillHint: 'Prefill 播放按整块算子阶段推进，不模拟逐 token 串行执行。',
    currentToken: '当前 token', tokenPrefix: 't', tokenHint: '拖动或点击 token 会从该 token 的第一阶段开始检查完整 Decode 路径。',
    exactScores: 'Q/K/V 输入', exactMask: '相关性计算', exactAggregate: '遮罩与 Softmax', exactBottleneck: '加权聚合',
    linearMap: '特征映射', linearReorder: '外积写入', linearRecurrence: '状态累积', linearOutput: '归一化输出',
    glaProblem: '映射与门控', glaGate: '衰减旧状态', glaRecurrence: '写入新状态', glaOutput: '选择性输出',
    stage: '当前阶段', principle: '原理', equation: '核心公式', liveState: '实时变量', pseudocode: '伪代码', boundary: '能力边界',
    pipelineTitle: '自回归 Decode 流水线', pipelineRule: '同一个 token 从左到右走完整条路径；生成输出后，下一个 token 才进入流水线。', pipelineRunning: 'Decode 自动执行中', pipelinePaused: '已暂停',
    stageComplete: '序列完成', stagePassed: '本 token 已流过', stagePending: '等待当前 token', activeStageLegend: '唯一执行阶段', glaRelationTitle: 'GLA 是朴素 Linear Attention 的门控扩展',
    glaRelationLead: '特征映射、固定状态和读取方式保持一致；关键变化只发生在状态更新：写入当前 token 前，先选择性衰减旧状态。',
    linearAccumulator: 'Linear：只累加', addForgetGate: '加入遗忘门', glaAccumulator: 'GLA：先衰减再累加',
    sameAtFirstToken: 't1 还没有历史状态可供遗忘，因此两种矩阵完全相同；播放到 t2 后，门控差异才会真实出现。',
    differenceAfterHistory: '历史已经写入：Linear 保留全部旧状态，GLA 先按当前门控衰减旧状态，再写入这个 token。', historyRetention: '旧状态保留率',
    logicalLayer: '逻辑层', physicalLayer: '物理层', currentWrite: '本次写入', historyState: '历史状态', updatedState: '更新后状态',
    query: '当前查询 qₜ', key: '当前键 kₜ', value: '当前值 vₜ', mappedQuery: '映射后 φ(qₜ)', mappedKey: '映射后 φ(kₜ)',
    score: '相关性分数', causalPrefix: '可见历史前缀', maskedFuture: '未来位置（遮罩）', attentionWeight: 'Softmax 权重', output: '输出 oₜ',
    exactScoreTitle: '当前 query 与所有历史 key 逐一匹配',
    exactScoreLead: '高亮行就是当前 token 的读取路径；每增加一个 token，都要多做一组两两比较。',
    exactMaskTitle: '只保留因果前缀，再把分数归一化',
    exactMaskLead: '当前 query 只能看到自己与过去。Softmax 把保留下来的分数转成总和为 1 的权重。',
    exactAggregateTitle: '权重沿数据流写入值向量',
    exactAggregateLead: '每个历史 value 按注意力权重贡献到当前输出，权重越大，数据流越亮。',
    exactInputTitle: '从输入生成当前计算所需的 Q、K、V',
    exactInputLead: '三个线性投影提供查询、匹配索引和值内容；后续算子始终沿这三条数据流工作。',
    exactBottleneckTitle: '瓶颈来自随 N 平方增长的比较面',
    exactBottleneckLead: 'FlashAttention 可以减少 HBM 往返，但不会改变精确注意力的二次计算关系。',
    linearMapTitle: '用正值特征映射替代 Softmax 核',
    linearMapLead: '映射把 q、k 送入可结合的乘积形式，为后续重排计算顺序创造条件。',
    linearReorderTitle: '先压缩历史，再让 query 读取',
    linearReorderLead: '右侧路径不再构造 N×N 分数矩阵，而是先得到固定大小的历史摘要。',
    linearOuterTitle: '把当前 key 与 value 写成一个外积增量',
    linearOuterLead: '每个 token 只产生一个固定大小的状态增量；这是递归状态真正接收的新信息。',
    linearRecurrenceTitle: '当前 token 只写入一个外积增量',
    linearRecurrenceLead: '黄色矩阵是本次写入；它与历史状态相加，得到可供后续 token 读取的新状态。',
    linearOutputTitle: 'query 从 S 读取内容，再由 z 校准尺度',
    linearOutputLead: 'S 聚合值信息，z 聚合归一化质量；两者缺一不可。',
    glaProblemTitle: '固定状态会持续累积无关历史',
    glaProblemLead: '朴素递归只会相加，不会主动遗忘。长序列中，过时信息会继续参与后续读取。',
    glaGateTitle: '门控决定每个状态通道保留多少',
    glaGateLead: '门控不是一个装饰性分数，而是直接乘到旧状态上，使不同通道以不同速度衰减。',
    glaRecurrenceTitle: '先衰减旧状态，再写入当前信息',
    glaRecurrenceLead: '观察旧矩阵先被门控变暗，然后本次外积以高亮增量写入。',
    glaOutputTitle: '选择性记忆改变最终读取结果',
    glaOutputLead: '门控输出压低旧噪声贡献，同时保留与当前 query 更相关的状态通道。',
    glaMapGateTitle: '同时生成特征映射与当前 token 的遗忘门',
    glaMapGateLead: 'GLA 复用 Linear Attention 的特征映射，并额外从当前输入生成逐通道保留率。',
    glaDecayTitle: '先让遗忘门作用到上一时刻状态',
    glaDecayLead: '保留率低的历史通道先衰减；这是 GLA 与朴素 Linear Attention 唯一关键的结构差异。',
    glaWriteTitle: '把当前 token 的外积增量写入衰减后的状态',
    glaWriteLead: '门控只处理旧历史，当前 token 的信息随后完整写入，形成供后续读取的新状态。',
    pairwiseScores: '逐键匹配', scoreMatrix: '因果分数矩阵（紧凑视图）', activeQueryRow: '当前 query 行',
    weightedValues: '按权重汇聚历史 value', contribution: '贡献',
    scoreStorage: '分数矩阵存储', recurrentStorage: '递归状态存储', scoreCellCount: '分数单元数',
    growsQuadratically: 'N 翻倍，分数单元变为 4 倍', fixedAcrossSequence: '不随序列长度 N 增长',
    hbmTraffic: 'HBM 中间结果', computeSurface: '两两比较计算面', fixedState: '固定状态 S 与 z',
    beforeMap: '映射前', afterMap: '映射后（全部为正）',
    leftAssociation: '先生成 N×N 注意力面', rightAssociation: '先生成固定大小状态', recommended: 'Linear 路径',
    nByN: 'N × N', dkByDv: 'dₖ × dᵥ', noScoreMatrix: '不物化分数矩阵',
    outerProduct: '外积增量 ΔSₜ', previousState: '旧状态 Sₜ₋₁', decayedState: '门控后的旧状态', newState: '新状态 Sₜ',
    normalizerUpdate: '归一化状态同步更新', previousNormalizer: '旧 z', newNormalizer: '新 z',
    numerator: '内容读取 φ(qₜ)ᵀSₜ', denominator: '尺度校准 φ(qₜ)ᵀzₜ',
    staleState: '过时信息仍残留', relevantState: '当前相关信息', ungated: '无门控', gated: 'GLA 门控',
    gateStrength: '遗忘强度', retention: '逐通道保留率 αₜ', retain: '保留', forget: '衰减',
    plainOutput: '无门控输出', gatedOutput: '门控输出', noiseContribution: '旧噪声贡献', relevantContribution: '相关信号贡献',
    currentPulse: '当前 token 正在执行', sampledDimensions: '画板抽样展示 4 个维度，尺寸标签使用实际实验参数。',
    exactMetric: '精确，但计算与存储随 N² 增长', linearMetric: '固定状态，但属于核替换近似', glaMetric: '固定状态并具备选择性遗忘',
    exactBoundary: '精确保持 Softmax 归一化关系；无法压成同样的固定递归状态。',
    linearBoundary: '效率来自核替换与结合律重排，因此不再与 Softmax 完全等价。',
    glaBoundary: '门控改善状态管理，但有限状态仍不能保证保留任意长距离细节。',
    softmaxCode0: ['q_t = x_t @ W_q', 'k_t = x_t @ W_k', 'v_t = x_t @ W_v', '# feed three downstream paths'],
    softmaxCode1: ['for key j in prefix:', '  score[j] = dot(q_t, k_j) / sqrt(d_k)', '# one score per visible key', 'cache(score)'],
    softmaxCode2: ['score[future] = -inf', 'weights = softmax(score)', 'assert sum(weights) == 1', '# route visible values'],
    softmaxCode3: ['o_t = zeros(d_v)', 'for j in prefix:', '  o_t += weights[j] * v_j', 'return o_t'],
    linearCode0: ['q_bar = phi(q_t)', 'k_bar = phi(k_t)', 'assert all(q_bar > 0)', 'assert all(k_bar > 0)'],
    linearCode1: ['k_bar = phi(k_t)', 'delta = outer(k_bar, v_t)', 'delta_z = k_bar', '# fixed-size token write'],
    linearCode2: ['S_t = S_prev + delta', 'z_t = z_prev + phi(k_t)', 'cache(S_t, z_t)', '# no selective forgetting'],
    linearCode3: ['numerator = phi(q_t).T @ S_t', 'denominator = phi(q_t).T @ z_t + eps', 'o_t = numerator / denominator', 'return o_t'],
    glaCode0: ['k_bar = phi(k_t)', 'alpha_t = sigmoid(W_alpha @ x_t + b)', 'delta = outer(k_bar, v_t)', '# Linear backbone + gate'],
    glaCode1: ['S_old = alpha_t * S_prev', 'z_old = alpha_t * z_prev', '# decay stale history first', 'cache(S_old, z_old)'],
    glaCode2: ['delta = phi(k_t) @ v_t.T', 'S_t = S_old + delta', 'z_t = z_old + phi(k_t)', 'cache(S_t, z_t)'],
    glaCode3: ['numerator = phi(q_t).T @ S_t', 'denominator = phi(q_t).T @ z_t + eps', 'o_t = numerator / denominator', 'return o_t'],
  },
  en: {
    softmax: 'Softmax', architectureShortTitle: 'How is history stored?', stageProgress: 'Block operator stages',
    title: 'Linear Attention Interactive Lab',
    subtitle: 'Understand Linear Attention through history representation, memory growth, compute, and information loss',
    exact: 'Exact Softmax', linear: 'Naive Linear', gla: 'GLA', softmaxVs: 'Softmax vs',
    reset: 'Reset', play: 'Play', pause: 'Pause', next: 'Next step', zh: '中文', en: 'EN',
    experiment: 'Scale and dimensions', sequenceLength: 'Sequence length N', contextLength: 'Context length N', keyDim: 'Key dimension dₖ', valueDim: 'Value dimension dᵥ', comparisonTarget: 'Comparison target',
    designLevel: 'Design level', architectureTitle: 'History representation: per-token KV cache vs fixed compressed state', architectureLead: 'Softmax preserves independently addressable history slots; Linear/GLA merge all history into a fixed-size state. See this representation tradeoff before opening the per-token implementation pipeline.',
    executionContext: 'Execution context', decode: 'Decode', prefill: 'Prefill / training', growingKvCache: 'KV cache growing with N', pairwiseAttentionSurface: 'Full pairwise sequence surface', addressable: 'Addressable', fixedRecurrentState: 'Fixed recurrent state', gatedFixedState: 'Fixed state with selective forgetting', compressed: 'Compressed summary',
    softmaxDecodeVisual: 'The current query connects to a growing KV cache', softmaxPrefillVisual: 'The N by N causal pairwise surface of Softmax', softmaxDecodeLead: 'Every historical token keeps its own key and value. The current query can match them separately, while KV memory and per-step reads grow with context.', softmaxPrefillLead: 'The full sequence can be processed in parallel, but the logical N×N causal comparison surface remains and quadruples when sequence length doubles.',
    logicalCells: 'logical score cells', moreSlots: 'additional KV slots', chunksEnter: 'Parallel chunks enter', tokensEnter: 'History tokens enter', fixedShape: 'fixed shape', linearCompressedLead: 'History no longer has separate slots; outer-product writes merge into the same S and z whose shape is independent of N.', glaCompressedLead: 'GLA keeps the same fixed-state structure, but decays old state before writing the current token to manage finite capacity.',
    persistentMemory: 'Persistent history memory', singleTokenWork: 'Single-token read', historyAccess: 'History access', addressableHistory: 'Each KV slot can be matched separately', compressedHistory: 'Only the merged state summary is readable', growthWithN: 'Growth with N', linearGrowth: 'Memory and per-step work grow linearly', fixedGrowth: 'State shape and per-step work stay roughly fixed',
    logicalIntermediate: 'Logical intermediate', sequenceWork: 'Full-sequence work', parallelForm: 'Parallel form', matrixParallel: 'Matrix parallel', chunkwiseGla: 'Hardware-efficient chunkwise parallel', prefixOrChunk: 'Prefix scan or chunkwise parallel', informationForm: 'Information organization', pairwiseSurface: 'Preserves pairwise relation surface', compressedSummary: 'Merged into a finite state summary', comparisonAxis: 'Comparison axis', elements: 'elements',
    currentMemoryRatio: 'At the current N, Softmax Decode KV elements are about', breakEvenAt: 'Estimated crossover near', notYetSaving: 'At this short context, fixed state has not yet produced a memory advantage', prefillFlashNote: 'This compares the logical compute surface. FlashAttention can avoid materializing the full N² score matrix, but does not remove exact attention pairwise work.',
    compressionCostTitle: 'Compression is not free: addressable history becomes finite state', compressionCostLead: 'When similar keys map to different values, Softmax can still select them separately. Linear merges them into one state and may introduce collision, mixing, and lost detail.', separateSlots: 'Softmax: slots stay separate', querySelectsB: 'query selects B', softmaxRecallResult: 'Result: B remains directly addressable and other history is not permanently merged into its slot.', mergedState: 'Fixed state: A/B/C merge', noTokenAddress: 'No token address', linearCollisionResult: 'Result: reads come from a mixed state, so finite dimensions can create state collisions.', glaCollisionResult: 'Result: gating can suppress old collisions, but may also forget history that is still useful.',
    prefillFlowTitle: 'One-shot Prefill operator flow: each stage handles a matrix or chunk, not a serial token sweep', prefillSoftmax0: 'Project Q/K/V in parallel', prefillSoftmax1: 'Build causal score surface', prefillSoftmax2: 'Mask and Softmax', prefillSoftmax3: 'Matrix aggregation over V', prefillLinear0: 'Parallel feature map', prefillLinear1: 'Build chunk summaries', prefillLinear2: 'Prefix/chunk scan', prefillLinear3: 'Read outputs in parallel', prefillGla0: 'Map and predict gates', prefillGla1: 'Parallel inside chunks', prefillGla2: 'Gated state across chunks', prefillGla3: 'Read outputs in parallel',
    implementationDetailTitle: 'Second layer: expand the real Decode path of one token', implementationDetailLead: 'The design comparison explains why history is compressed. This pipeline only explains how the current token matches, writes, and reads history.', detailAlgorithm: 'Detail algorithm', demoSequence: '8-token miniature', prefillHint: 'Prefill playback advances by whole-matrix operator stages and does not simulate a serial token sweep.',
    currentToken: 'Current token', tokenPrefix: 't', tokenHint: 'Selecting a token restarts at its first stage so you can inspect the full Decode path.',
    exactScores: 'Q/K/V input', exactMask: 'Pairwise scores', exactAggregate: 'Mask & Softmax', exactBottleneck: 'Value aggregation',
    linearMap: 'Feature map', linearReorder: 'Outer-product write', linearRecurrence: 'State accumulation', linearOutput: 'Normalized read',
    glaProblem: 'Map & gate', glaGate: 'Decay old state', glaRecurrence: 'Write new state', glaOutput: 'Selective output',
    stage: 'Current stage', principle: 'Principle', equation: 'Core equation', liveState: 'Live variables', pseudocode: 'Pseudocode', boundary: 'Boundary',
    pipelineTitle: 'Autoregressive Decode pipeline', pipelineRule: 'One token traverses the full path from left to right; only after its output is produced does the next token enter.', pipelineRunning: 'Decode auto running', pipelinePaused: 'Paused',
    stageComplete: 'Sequence complete', stagePassed: 'Passed by this token', stagePending: 'Waiting for token', activeStageLegend: 'Only executing stage', glaRelationTitle: 'GLA is a gated extension of naive Linear Attention',
    glaRelationLead: 'The feature map, fixed state, and read path stay the same. The key change is in state update: selectively decay old state before writing the current token.',
    linearAccumulator: 'Linear: accumulate only', addForgetGate: 'add forget gate', glaAccumulator: 'GLA: decay then add',
    sameAtFirstToken: 'At t1 there is no previous state to forget, so both matrices are identical. The gated difference appears from t2 onward.',
    differenceAfterHistory: 'History now exists: Linear keeps all old state, while GLA decays it with the current gate before writing this token.', historyRetention: 'Old-state retention',
    logicalLayer: 'Logical layer', physicalLayer: 'Physical layer', currentWrite: 'Current write', historyState: 'History state', updatedState: 'Updated state',
    query: 'Current query qₜ', key: 'Current key kₜ', value: 'Current value vₜ', mappedQuery: 'Mapped φ(qₜ)', mappedKey: 'Mapped φ(kₜ)',
    score: 'Similarity score', causalPrefix: 'Visible causal prefix', maskedFuture: 'Future (masked)', attentionWeight: 'Softmax weight', output: 'Output oₜ',
    exactScoreTitle: 'Match the current query with every previous key',
    exactScoreLead: 'The highlighted row is the current read path. Every new token adds another set of pairwise comparisons.',
    exactMaskTitle: 'Keep the causal prefix, then normalize its scores',
    exactMaskLead: 'The current query sees only itself and the past. Softmax converts retained scores into weights that sum to one.',
    exactAggregateTitle: 'Weights route value vectors into the output',
    exactAggregateLead: 'Each historical value contributes according to its attention weight; stronger flows are drawn brighter.',
    exactInputTitle: 'Project the input into Q, K, and V for this computation',
    exactInputLead: 'The three projections provide the query, matching index, and value content used by every downstream operator.',
    exactBottleneckTitle: 'The bottleneck is the pairwise surface growing with N squared',
    exactBottleneckLead: 'FlashAttention reduces HBM traffic, but exact attention still performs quadratic pairwise work.',
    linearMapTitle: 'Replace the Softmax kernel with a positive feature map',
    linearMapLead: 'The map moves q and k into an associative product form that can be reordered.',
    linearReorderTitle: 'Compress history first, then let the query read it',
    linearReorderLead: 'The right path avoids an N×N score matrix and builds a fixed-size summary instead.',
    linearOuterTitle: 'Write the current key and value as one outer-product update',
    linearOuterLead: 'Each token produces one fixed-size state delta—the actual new information accepted by recurrent state.',
    linearRecurrenceTitle: 'The current token writes one outer-product update',
    linearRecurrenceLead: 'The amber matrix is the current write. Adding it to history produces the state consumed by later tokens.',
    linearOutputTitle: 'Read content from S and calibrate its scale with z',
    linearOutputLead: 'S aggregates values while z carries normalization mass; both are required.',
    glaProblemTitle: 'A fixed state keeps accumulating irrelevant history',
    glaProblemLead: 'Naive recurrence only adds and never forgets, so stale information keeps influencing later reads.',
    glaGateTitle: 'A gate decides how much of every state channel survives',
    glaGateLead: 'The gate directly multiplies the old state, allowing channels to decay at different rates.',
    glaRecurrenceTitle: 'Decay old state before writing current information',
    glaRecurrenceLead: 'Watch the old matrix dim under the gate, then accept the highlighted outer-product update.',
    glaOutputTitle: 'Selective memory changes the final read',
    glaOutputLead: 'Gating suppresses stale noise while preserving channels more relevant to the current query.',
    glaMapGateTitle: 'Build the feature map and this token’s forget gate together',
    glaMapGateLead: 'GLA reuses the Linear Attention feature map and additionally predicts a per-channel retention rate from the current input.',
    glaDecayTitle: 'Apply the forget gate to the previous state first',
    glaDecayLead: 'Low-retention history channels decay here. This is the key structural difference from naive Linear Attention.',
    glaWriteTitle: 'Write the current outer-product update into the decayed state',
    glaWriteLead: 'The gate acts only on old history; current-token information is then written into the state consumed by later reads.',
    pairwiseScores: 'Pairwise matches', scoreMatrix: 'Causal score matrix (compact)', activeQueryRow: 'Current query row', weightedValues: 'Aggregate historical values', contribution: 'Contribution',
    scoreStorage: 'Score storage', recurrentStorage: 'Recurrent storage', scoreCellCount: 'Score cells', growsQuadratically: 'Doubling N quadruples score cells', fixedAcrossSequence: 'Independent of sequence length N',
    hbmTraffic: 'HBM intermediates', computeSurface: 'Pairwise compute surface', fixedState: 'Fixed S and z state', beforeMap: 'Before mapping', afterMap: 'After mapping (positive)',
    leftAssociation: 'Build an N×N attention surface', rightAssociation: 'Build a fixed-size state first', recommended: 'Linear path', nByN: 'N × N', dkByDv: 'dₖ × dᵥ', noScoreMatrix: 'No materialized score matrix',
    outerProduct: 'Outer-product update ΔSₜ', previousState: 'Previous state Sₜ₋₁', decayedState: 'Gated previous state', newState: 'New state Sₜ', normalizerUpdate: 'Update normalizer in lockstep', previousNormalizer: 'Previous z', newNormalizer: 'New z',
    numerator: 'Content read φ(qₜ)ᵀSₜ', denominator: 'Scale calibration φ(qₜ)ᵀzₜ', staleState: 'Stale information remains', relevantState: 'Currently relevant information', ungated: 'Ungated', gated: 'GLA gated',
    gateStrength: 'Forgetting strength', retention: 'Per-channel retention αₜ', retain: 'Retain', forget: 'Decay', plainOutput: 'Ungated output', gatedOutput: 'Gated output', noiseContribution: 'Stale noise contribution', relevantContribution: 'Relevant signal contribution',
    currentPulse: 'Current token executing', sampledDimensions: 'The canvas samples four dimensions while labels use the actual experiment sizes.',
    exactMetric: 'Exact, with compute and storage growing as N²', linearMetric: 'Fixed state, but based on a kernel approximation', glaMetric: 'Fixed state with selective forgetting',
    exactBoundary: 'Preserves exact Softmax normalization and cannot be compressed into the same fixed recurrent state.',
    linearBoundary: 'Efficiency comes from kernel replacement and reassociation, so it is not exactly equivalent to Softmax.',
    glaBoundary: 'Gating improves state management, but a finite state cannot retain arbitrary long-range detail.',
    softmaxCode0: ['q_t = x_t @ W_q', 'k_t = x_t @ W_k', 'v_t = x_t @ W_v', '# feed three downstream paths'],
    softmaxCode1: ['for key j in prefix:', '  score[j] = dot(q_t, k_j) / sqrt(d_k)', '# one score per visible key', 'cache(score)'],
    softmaxCode2: ['score[future] = -inf', 'weights = softmax(score)', 'assert sum(weights) == 1', '# route visible values'],
    softmaxCode3: ['o_t = zeros(d_v)', 'for j in prefix:', '  o_t += weights[j] * v_j', 'return o_t'],
    linearCode0: ['q_bar = phi(q_t)', 'k_bar = phi(k_t)', 'assert all(q_bar > 0)', 'assert all(k_bar > 0)'],
    linearCode1: ['k_bar = phi(k_t)', 'delta = outer(k_bar, v_t)', 'delta_z = k_bar', '# fixed-size token write'],
    linearCode2: ['S_t = S_prev + delta', 'z_t = z_prev + phi(k_t)', 'cache(S_t, z_t)', '# no selective forgetting'],
    linearCode3: ['numerator = phi(q_t).T @ S_t', 'denominator = phi(q_t).T @ z_t + eps', 'o_t = numerator / denominator', 'return o_t'],
    glaCode0: ['k_bar = phi(k_t)', 'alpha_t = sigmoid(W_alpha @ x_t + b)', 'delta = outer(k_bar, v_t)', '# Linear backbone + gate'],
    glaCode1: ['S_old = alpha_t * S_prev', 'z_old = alpha_t * z_prev', '# decay stale history first', 'cache(S_old, z_old)'],
    glaCode2: ['delta = phi(k_t) @ v_t.T', 'S_t = S_old + delta', 'z_t = z_old + phi(k_t)', 'cache(S_t, z_t)'],
    glaCode3: ['numerator = phi(q_t).T @ S_t', 'denominator = phi(q_t).T @ z_t + eps', 'o_t = numerator / denominator', 'return o_t'],
  },
};

const titleKeys = {
  exact: ['exactInputTitle', 'exactScoreTitle', 'exactMaskTitle', 'exactAggregateTitle'],
  linear: ['linearMapTitle', 'linearOuterTitle', 'linearRecurrenceTitle', 'linearOutputTitle'],
  gla: ['glaMapGateTitle', 'glaDecayTitle', 'glaWriteTitle', 'glaOutputTitle'],
};

const leadKeys = {
  exact: ['exactInputLead', 'exactScoreLead', 'exactMaskLead', 'exactAggregateLead'],
  linear: ['linearMapLead', 'linearOuterLead', 'linearRecurrenceLead', 'linearOutputLead'],
  gla: ['glaMapGateLead', 'glaDecayLead', 'glaWriteLead', 'glaOutputLead'],
};

const formulaKeys = {
  exact: ['projections', 'exactScore', 'exactWeights', 'exactOutput'],
  linear: ['featureMap', 'outerUpdate', 'state', 'linearOutput'],
  gla: ['glaMapGate', 'glaDecay', 'glaWrite', 'linearOutput'],
};

export const getStageCopy = (mode, step, t) => ({
  title: t(titleKeys[mode][step]),
  lead: t(leadKeys[mode][step]),
  formula: FORMULAS[formulaKeys[mode][step]],
  code: t(`${mode === 'exact' ? 'softmax' : mode}Code${step}`),
  boundary: t(`${mode}Boundary`),
  activeLine: step === 0 ? 0 : step === 1 ? 1 : step === 2 ? 2 : 1,
});
